//
// Created by yiak on 2020/8/27.
//
#pragma once

#ifndef SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_BTREE_ACCESSOR_H
#define SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_BTREE_ACCESSOR_H


class btree_accessor {

};


#endif //SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_BTREE_ACCESSOR_H
