//
// Created by yiak on 2021/7/1.
//

#ifndef SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_MAPBLOCK_H
#define SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_MAPBLOCK_H


class RuntimeBlock {

};


#endif //SEMANTIC_VISUAL_SUPPORTED_ODEMETRY_MAPBLOCK_H
